export const SET_CART_LIST = 'SET_CART_LIST'

export const ADD_GOOD_COUNT = 'ADD_GOOD_COUNT'

export const DECREASE_GOOD_COUNT = 'DECREASE_GOOD_COUNT'

export const SET_GOOD_COUNT = 'SET_GOOD_COUNT'

export const REMOVE_GOOD = 'REMOVE_GOOD'

export const SET_LOGIN_STATE = 'SET_LOGIN_STATE'

export const SET_LOGIN_VISIBLE = 'SET_LOGIN_VISIBLE'

export const SET_LOGIN_ACTION = 'SET_LOGIN_ACTION'

export const SET_USER_AVATAR = 'SET_USER_AVATAR'

export const SET_USER_NAME = 'SET_USER_NAME'
