export const SET_CART_LIST = 'SET_CART_LIST'

export const ADD_GOODS_COUNT = 'ADD_GOODS_COUNT'

export const DECREASE_GOODS_COUNT = 'DECREASE_GOODS_COUNT'

export const SET_GOODS_COUNT = 'SET_GOODS_COUNT'

export const REMOVE_GOODS = 'REMOVE_GOODS'

export const SET_LOGIN_STATE = 'SET_LOGIN_STATE'

export const SET_LOGIN_VISIBLE = 'SET_LOGIN_VISIBLE'

export const SET_LOGIN_ACTION = 'SET_LOGIN_ACTION'

export const SET_USER_ID = 'SET_USER_ID'

export const SET_USER_AVATAR = 'SET_USER_AVATAR'

export const SET_USER_NAME = 'SET_USER_NAME'

export const SET_USER_MENU_ACTIVE_NAME = 'SET_USER_MENU_ACTIVE_NAME'
